---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: playground
  namespace: default
spec:
  interval: 5m0s
  url: oci://acrplayground8mpz04.azurecr.io/charts
  type: "oci"
  secretRef:
    name: "regcred"