apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: laravel
  namespace: cluster-config
spec:
  chart:
    spec:
      version: "0.0.5"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: laravel.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
